# Získejte zdarma na https://polygon.io/dashboard/signup
# Pro lokální testování vložte svůj klíč sem.
# Pro nasazení na Streamlit Cloud přidejte klíč v nastavení secrets.
POLYGON_API_KEY = "VÁŠ_KLÍČ_ZDE"
